/**
 * Curated Lucide icon registry (local, bundle-friendly).
 *
 * Previously the app did `import * as Icons from 'lucide-preact'` with dynamic
 * lookup, pulling the full lucide module (~123 KB) into the single-file bundle.
 * Now the icon set is rendered by the local `Icon` component (Icon.tsx) from
 * static SVG path data (iconPaths.ts, generated by scripts/extractIcons.mjs),
 * keeping the same `spec` contract (PascalCase export name stored in LinkItem.icon).
 *
 * Notes:
 * - Brand icons (Github, Youtube, ...) no longer exist in lucide >= 2025;
 *   site icons are resolved automatically via the favicon chain instead.
 * - `spec` is the stored value kept in LinkItem.icon (PascalCase export name).
 */

import { h, type ComponentType } from 'preact';
import { Icon, type IconProps } from './Icon';
import { ICON_PATHS } from './iconPaths';

/** A pre-bound icon component: `name` is already fixed, callers pass size/class only. */
export type IconComponent = ComponentType<Omit<IconProps, 'name'>>;

export interface IconEntry {
  /** PascalCase export name (also the stored spec value) */
  name: string;
  spec: string;
  icon: IconComponent;
}

const iconCache = new Map<string, IconComponent>();

/** Stable per-name component so memoized rows keep identity across renders. */
export const iconComponentFor = (name: string): IconComponent => {
  let cmp = iconCache.get(name);
  if (!cmp) {
    cmp = (props) => h(Icon, { name, ...props });
    iconCache.set(name, cmp);
  }
  return cmp;
};

/** Curated list shown by the icon picker (alphabetical). */
export const ICON_LIST: IconEntry[] = Object.keys(ICON_PATHS)
  .sort()
  .map((name) => ({ name, spec: name, icon: iconComponentFor(name) }));

/** Lowercase-keyed lookup, precomputed once (no per-keystroke lowercasing). */
const ICON_INDEX = new Map<string, IconEntry>(
  ICON_LIST.map((entry) => [entry.name.toLowerCase(), entry])
);

/**
 * Resolves a stored icon spec to an icon component.
 * Exact match first, then case-insensitive. Returns null for unknown specs.
 */
export const getLucideIcon = (spec?: string): IconComponent | null => {
  if (!spec) return null;
  const trimmed = spec.trim();
  if (!trimmed) return null;
  const exact = ICON_LIST.find((en) => en.spec === trimmed);
  if (exact) return exact.icon;
  return ICON_INDEX.get(trimmed.toLowerCase())?.icon ?? null;
};

/** True when the spec names a curated Lucide icon (not a URL/SVG/favicon spec). */
export const isLucideIconSpec = (spec?: string): boolean => {
  if (!spec) return false;
  const trimmed = spec.trim();
  return (
    trimmed.length > 0 &&
    !trimmed.startsWith('http') &&
    !trimmed.startsWith('data:') &&
    !trimmed.startsWith('/') &&
    !trimmed.includes('<svg') &&
    getLucideIcon(trimmed) !== null
  );
};

/**
 * Searches the curated registry by lowercase substring on the icon name.
 * The lowercase index is precomputed at module load.
 */
export const searchLucideIcons = (query: string, limit = 60): IconEntry[] => {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const results: IconEntry[] = [];
  for (const entry of ICON_LIST) {
    if (entry.name.toLowerCase().includes(q)) {
      results.push(entry);
      if (results.length >= limit) break;
    }
  }
  return results;
};
