import { h, type ComponentType, type JSX } from 'preact';
import { ICON_PATHS } from './iconPaths';

export interface IconProps {
  /** Icon name (PascalCase spec, e.g. 'Search', 'Zap') — same contract as the old lucide imports. */
  name: string;
  size?: number;
  class?: string | undefined;
  style?: JSX.CSSProperties | undefined;
  title?: string | undefined;
  strokeWidth?: number;
}

export const ICON_SVG_ATTRS: Record<string, unknown> = {
  xmlns: 'http://www.w3.org/2000/svg',
  viewBox: '0 0 24 24',
  fill: 'none',
  stroke: 'currentColor',
  'stroke-linecap': 'round',
  'stroke-linejoin': 'round'
};

/**
 * Local Lucide-compatible icon renderer.
 *
 * Replaces the runtime lucide-preact dependency with static SVG path data
 * (src/components/iconPaths.ts, generated by scripts/extractIcons.mjs) so the
 * single-file bundle no longer carries the ~123 KB lucide module. Rendering
 * attributes mirror lucide exactly (24px viewBox, stroke 2, round caps).
 */
export const Icon: ComponentType<IconProps> = ({
  name,
  size = 24,
  class: cls,
  style,
  title,
  strokeWidth = 2
}) => {
  const inner = ICON_PATHS[name];
  if (inner === undefined) return null;
  const svgInner = title ? `<title>${title}</title>${inner}` : inner;
  return h('svg', {
    ...ICON_SVG_ATTRS,
    width: size,
    height: size,
    'stroke-width': strokeWidth,
    class: cls,
    style,
    'aria-hidden': title ? undefined : 'true',
    role: title ? 'img' : undefined,
    dangerouslySetInnerHTML: { __html: svgInner }
  });
};
