/**
 * Static curated Lucide icon registry.
 *
 * Previously the app did `import * as Icons from 'lucide-preact'` with dynamic
 * lookup, which pulled all ~6000 exports (~900KB) into the single-file bundle.
 * A curated static registry keeps only the icons the UI can actually offer,
 * restoring tree-shaking (bundle target: <200KB).
 *
 * Notes:
 * - Brand icons (Github, Youtube, ...) no longer exist in lucide >= 2025;
 *   site icons are resolved automatically via the favicon chain instead.
 * - `spec` is the stored value kept in LinkItem.icon (PascalCase export name).
 */

import type { LucideIcon } from 'lucide-preact';
import {
  Activity,
  Airplay,
  AlarmClock,
  AlertCircle,
  AlertTriangle,
  Anchor,
  Aperture,
  Apple,
  Archive,
  ArrowRight,
  ArrowUpRight,
  Atom,
  Award,
  Baby,
  BarChart3,
  Barcode,
  Beaker,
  Bell,
  BellRing,
  Bike,
  Binary,
  Bird,
  Bitcoin,
  Book,
  BookMarked,
  BookOpen,
  Bookmark,
  Bot,
  Box,
  Braces,
  Brain,
  BrainCircuit,
  Briefcase,
  Bug,
  Building,
  Building2,
  Calculator,
  Calendar,
  CalendarDays,
  Camera,
  Car,
  Cat,
  CheckCircle,
  ChevronDown,
  ChevronUp,
  ClipboardList,
  Clock,
  Cloud,
  CloudDownload,
  CloudSun,
  Code,
  Code2,
  Coffee,
  Columns,
  Compass,
  Cpu,
  CreditCard,
  Crown,
  Database,
  Dice5,
  Dna,
  Dog,
  DollarSign,
  Download,
  Dumbbell,
  Edit,
  Edit3,
  Euro,
  ExternalLink,
  Eye,
  EyeOff,
  Feather,
  File,
  FileText,
  Files,
  Film,
  Fish,
  Flag,
  Flame,
  FlaskConical,
  Flower2,
  Folder,
  FolderOpen,
  Frown,
  Gamepad2,
  Gem,
  Ghost,
  Gift,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Globe,
  Globe2,
  GraduationCap,
  Grid,
  Hammer,
  HardDrive,
  Headphones,
  Heart,
  HeartPulse,
  HelpCircle,
  Home,
  Hospital,
  Image,
  Images,
  Inbox,
  Info,
  Kanban,
  KanbanSquare,
  Key,
  Landmark,
  Languages,
  Laptop,
  Layers,
  Leaf,
  Library,
  Lightbulb,
  LineChart,
  Link,
  Link2,
  List,
  Lock,
  Mail,
  MailOpen,
  Map as MapIcon,
  MapPin,
  Medal,
  Megaphone,
  Meh,
  MessageCircle,
  MessageSquare,
  Mic,
  Microscope,
  Monitor,
  Moon,
  Mouse,
  Music,
  Music2,
  Music4,
  Navigation,
  Network,
  Newspaper,
  NotebookPen,
  Orbit,
  Package,
  Paintbrush,
  Palette,
  Paperclip,
  PauseCircle,
  Pen,
  PenTool,
  Pencil,
  Phone,
  PieChart,
  Pill,
  Pizza,
  Plane,
  Play,
  PlayCircle,
  Podcast,
  Printer,
  Puzzle,
  QrCode,
  Quote,
  Radio,
  Recycle,
  Rocket,
  Ruler,
  Satellite,
  School,
  Scissors,
  Search,
  Send,
  Server,
  Settings,
  Settings2,
  Share,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sigma,
  Smartphone,
  Smile,
  Sparkles,
  Star,
  Stethoscope,
  Sun,
  Syringe,
  Tablet,
  Tag,
  Tags,
  Target,
  Telescope,
  Terminal,
  ThumbsDown,
  ThumbsUp,
  Timer,
  ToolCase,
  Toolbox,
  Train,
  Trash2,
  TreePine,
  TrendingUp,
  Trophy,
  Tv,
  Umbrella,
  Unlock,
  Upload,
  User,
  UserPlus,
  Users,
  Video,
  Volume2,
  Wallet,
  Wand2,
  Watch,
  Wifi,
  Wrench,
  XCircle,
  Zap,
  ZoomIn,
} from 'lucide-preact';

export type IconComponent = LucideIcon;

export interface IconEntry {
  /** PascalCase export name (also the stored spec value) */
  name: string;
  spec: string;
  icon: IconComponent;
}

const e = (name: string, icon: IconComponent): IconEntry => ({ name, spec: name, icon });

/** Curated list shown by the icon picker. Keep alphabetized. */
export const ICON_LIST: IconEntry[] = [
  e('Activity', Activity),
  e('Airplay', Airplay),
  e('AlarmClock', AlarmClock),
  e('AlertCircle', AlertCircle),
  e('AlertTriangle', AlertTriangle),
  e('Anchor', Anchor),
  e('Aperture', Aperture),
  e('Apple', Apple),
  e('Archive', Archive),
  e('ArrowRight', ArrowRight),
  e('ArrowUpRight', ArrowUpRight),
  e('Atom', Atom),
  e('Award', Award),
  e('Baby', Baby),
  e('BarChart3', BarChart3),
  e('Barcode', Barcode),
  e('Beaker', Beaker),
  e('Bell', Bell),
  e('BellRing', BellRing),
  e('Bike', Bike),
  e('Binary', Binary),
  e('Bird', Bird),
  e('Bitcoin', Bitcoin),
  e('Book', Book),
  e('BookMarked', BookMarked),
  e('BookOpen', BookOpen),
  e('Bookmark', Bookmark),
  e('Bot', Bot),
  e('Box', Box),
  e('Braces', Braces),
  e('Brain', Brain),
  e('BrainCircuit', BrainCircuit),
  e('Briefcase', Briefcase),
  e('Bug', Bug),
  e('Building', Building),
  e('Building2', Building2),
  e('Calculator', Calculator),
  e('Calendar', Calendar),
  e('CalendarDays', CalendarDays),
  e('Camera', Camera),
  e('Car', Car),
  e('Cat', Cat),
  e('CheckCircle', CheckCircle),
  e('ChevronDown', ChevronDown),
  e('ChevronUp', ChevronUp),
  e('ClipboardList', ClipboardList),
  e('Clock', Clock),
  e('Cloud', Cloud),
  e('CloudDownload', CloudDownload),
  e('CloudSun', CloudSun),
  e('Code', Code),
  e('Code2', Code2),
  e('Coffee', Coffee),
  e('Columns', Columns),
  e('Compass', Compass),
  e('Cpu', Cpu),
  e('CreditCard', CreditCard),
  e('Crown', Crown),
  e('Database', Database),
  e('Dice5', Dice5),
  e('Dna', Dna),
  e('Dog', Dog),
  e('DollarSign', DollarSign),
  e('Download', Download),
  e('Dumbbell', Dumbbell),
  e('Edit', Edit),
  e('Edit3', Edit3),
  e('Euro', Euro),
  e('ExternalLink', ExternalLink),
  e('Eye', Eye),
  e('EyeOff', EyeOff),
  e('Feather', Feather),
  e('File', File),
  e('FileText', FileText),
  e('Files', Files),
  e('Film', Film),
  e('Fish', Fish),
  e('Flag', Flag),
  e('Flame', Flame),
  e('FlaskConical', FlaskConical),
  e('Flower2', Flower2),
  e('Folder', Folder),
  e('FolderOpen', FolderOpen),
  e('Frown', Frown),
  e('Gamepad2', Gamepad2),
  e('Gem', Gem),
  e('Ghost', Ghost),
  e('Gift', Gift),
  e('GitBranch', GitBranch),
  e('GitCommit', GitCommit),
  e('GitMerge', GitMerge),
  e('GitPullRequest', GitPullRequest),
  e('Globe', Globe),
  e('Globe2', Globe2),
  e('GraduationCap', GraduationCap),
  e('Grid', Grid),
  e('Hammer', Hammer),
  e('HardDrive', HardDrive),
  e('Headphones', Headphones),
  e('Heart', Heart),
  e('HeartPulse', HeartPulse),
  e('HelpCircle', HelpCircle),
  e('Home', Home),
  e('Hospital', Hospital),
  e('Image', Image),
  e('Images', Images),
  e('Inbox', Inbox),
  e('Info', Info),
  e('Kanban', Kanban),
  e('KanbanSquare', KanbanSquare),
  e('Key', Key),
  e('Landmark', Landmark),
  e('Languages', Languages),
  e('Laptop', Laptop),
  e('Layers', Layers),
  e('Leaf', Leaf),
  e('Library', Library),
  e('Lightbulb', Lightbulb),
  e('LineChart', LineChart),
  e('Link', Link),
  e('Link2', Link2),
  e('List', List),
  e('Lock', Lock),
  e('Mail', Mail),
  e('MailOpen', MailOpen),
  e('Map', MapIcon),
  e('MapPin', MapPin),
  e('Medal', Medal),
  e('Megaphone', Megaphone),
  e('Meh', Meh),
  e('MessageCircle', MessageCircle),
  e('MessageSquare', MessageSquare),
  e('Mic', Mic),
  e('Microscope', Microscope),
  e('Monitor', Monitor),
  e('Moon', Moon),
  e('Mouse', Mouse),
  e('Music', Music),
  e('Music2', Music2),
  e('Music4', Music4),
  e('Navigation', Navigation),
  e('Network', Network),
  e('Newspaper', Newspaper),
  e('NotebookPen', NotebookPen),
  e('Orbit', Orbit),
  e('Package', Package),
  e('Paintbrush', Paintbrush),
  e('Palette', Palette),
  e('Paperclip', Paperclip),
  e('PauseCircle', PauseCircle),
  e('Pen', Pen),
  e('PenTool', PenTool),
  e('Pencil', Pencil),
  e('Phone', Phone),
  e('PieChart', PieChart),
  e('Pill', Pill),
  e('Pizza', Pizza),
  e('Plane', Plane),
  e('Play', Play),
  e('PlayCircle', PlayCircle),
  e('Podcast', Podcast),
  e('Printer', Printer),
  e('Puzzle', Puzzle),
  e('QrCode', QrCode),
  e('Quote', Quote),
  e('Radio', Radio),
  e('Recycle', Recycle),
  e('Rocket', Rocket),
  e('Ruler', Ruler),
  e('Satellite', Satellite),
  e('School', School),
  e('Scissors', Scissors),
  e('Search', Search),
  e('Send', Send),
  e('Server', Server),
  e('Settings', Settings),
  e('Settings2', Settings2),
  e('Share', Share),
  e('Share2', Share2),
  e('Shield', Shield),
  e('ShieldCheck', ShieldCheck),
  e('ShoppingBag', ShoppingBag),
  e('ShoppingCart', ShoppingCart),
  e('Sigma', Sigma),
  e('Smartphone', Smartphone),
  e('Smile', Smile),
  e('Sparkles', Sparkles),
  e('Star', Star),
  e('Stethoscope', Stethoscope),
  e('Sun', Sun),
  e('Syringe', Syringe),
  e('Tablet', Tablet),
  e('Tag', Tag),
  e('Tags', Tags),
  e('Target', Target),
  e('Telescope', Telescope),
  e('Terminal', Terminal),
  e('ThumbsDown', ThumbsDown),
  e('ThumbsUp', ThumbsUp),
  e('Timer', Timer),
  e('ToolCase', ToolCase),
  e('Toolbox', Toolbox),
  e('Train', Train),
  e('Trash2', Trash2),
  e('TreePine', TreePine),
  e('TrendingUp', TrendingUp),
  e('Trophy', Trophy),
  e('Tv', Tv),
  e('Umbrella', Umbrella),
  e('Unlock', Unlock),
  e('Upload', Upload),
  e('User', User),
  e('UserPlus', UserPlus),
  e('Users', Users),
  e('Video', Video),
  e('Volume2', Volume2),
  e('Wallet', Wallet),
  e('Wand2', Wand2),
  e('Watch', Watch),
  e('Wifi', Wifi),
  e('Wrench', Wrench),
  e('XCircle', XCircle),
  e('Zap', Zap),
  e('ZoomIn', ZoomIn),
];

/** Lowercase-keyed lookup, precomputed once (no per-keystroke lowercasing). */
const ICON_INDEX = new Map<string, IconEntry>(
  ICON_LIST.map(entry => [entry.name.toLowerCase(), entry]),
);

/**
 * Resolves a stored icon spec to an icon component.
 * Exact match first, then case-insensitive. Returns null for unknown specs.
 */
export const getLucideIcon = (spec?: string): IconComponent | null => {
  if (!spec) return null;
  const trimmed = spec.trim();
  if (!trimmed) return null;
  const exact = ICON_LIST.find(en => en.spec === trimmed);
  if (exact) return exact.icon;
  return ICON_INDEX.get(trimmed.toLowerCase())?.icon ?? null;
};

/** True when the spec names a curated Lucide icon (not a URL/SVG/favicon spec). */
export const isLucideIconSpec = (spec?: string): boolean => {
  if (!spec) return false;
  const trimmed = spec.trim();
  return (
    trimmed.length > 0 &&
    !trimmed.startsWith('http') &&
    !trimmed.startsWith('data:') &&
    !trimmed.startsWith('/') &&
    !trimmed.includes('<svg') &&
    getLucideIcon(trimmed) !== null
  );
};

/**
 * Searches the curated registry by lowercase substring on the icon name.
 * The lowercase index is precomputed at module load.
 */
export const searchLucideIcons = (query: string, limit = 60): IconEntry[] => {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const results: IconEntry[] = [];
  for (const entry of ICON_LIST) {
    if (entry.name.toLowerCase().includes(q)) {
      results.push(entry);
      if (results.length >= limit) break;
    }
  }
  return results;
};
