/**
 * Dev-only generator for src/components/iconPaths.ts.
 *
 * Reads the installed lucide-preact ESM entry to map every exported icon name
 * to its source file, then extracts each icon's inner SVG markup (elements +
 * attributes) verbatim. The output keeps rendering pixel-identical to the
 * original Lucide icons while removing the runtime lucide-preact dependency
 * from the single-file bundle.
 *
 * Regenerate (after bumping lucide-preact) with:
 *   bun scripts/extractIcons.mjs
 *
 * License note: Lucide icons are ISC-licensed. Data below is produced from
 * lucide-preact (ISC), see https://lucide.dev.
 */

import { readFileSync, writeFileSync } from 'node:fs';

const ROOT = new URL('..', import.meta.url);
const read = (rel) => readFileSync(new URL(rel, ROOT), 'utf8');

const entrySrc = read('node_modules/lucide-preact/dist/esm/lucide-preact.mjs');

// exportName -> icon file (all aliases in each export line resolve to one file)
const nameToFile = new Map();
for (const line of entrySrc.split('\n')) {
  const fm = line.match(/from ['"]\.\/icons\/([a-z0-9-]+)\.mjs['"]/);
  if (!fm) continue;
  for (const nm of line.matchAll(/default as ([A-Za-z0-9]+)/g)) nameToFile.set(nm[1], fm[1]);
}

const parseFile = (file) => {
  const src = read(`node_modules/lucide-preact/dist/esm/icons/${file}.mjs`);
  const m = src.match(/createLucideIcon\(\s*"[^"]+",\s*(\[[\s\S]*\])\s*\)/);
  if (!m) return null;
  const data = Function(`return ${m[1]}`)();
  return data
    .map(([tag, attrs]) => {
      // drop the redundant React `key:` prop from each element
      const { key: _key, ...rest } = attrs;
      const body = Object.entries(rest)
        .map(([k, v]) => `${k}="${v}"`)
        .join(' ');
      return `<${tag} ${body}/>`;
    })
    .join('');
};

// Collect icon names: curated registry list + all direct component imports.
const regSrc = read('src/components/iconRegistry.ts');
const names = new Set();
for (const m of regSrc.matchAll(/e\("([A-Za-z0-9]+)"/g)) names.add(m[1]);

const { execSync } = await import('node:child_process');
for (const f of execSync("grep -rl \"from 'lucide-preact'\" src/")
  .toString()
  .trim()
  .split('\n')) {
  const s = readFileSync(new URL(f, ROOT), 'utf8');
  const im = s.match(/import\s*\{([^}]+)\}\s*from\s*['"]lucide-preact['"]/);
  if (im) {
    for (const raw of im[1].split(',')) {
      const x = raw.trim().split(' as ')[0].trim();
      if (/^[A-Z]/.test(x)) names.add(x);
    }
  }
}

const missing = [];
let out = `/*
 * GENERATED FILE — do not edit by hand.
 * Generated by scripts/extractIcons.mjs from lucide-preact v1.27.0 (ISC).
 * Each value is the inner SVG markup for one Lucide icon, kept verbatim so
 * rendering is pixel-identical. Rendering is done by components/Icon.tsx.
 */

export const ICON_PATHS: Record<string, string> = {
`;
for (const iconName of [...names].sort()) {
  const file = nameToFile.get(iconName);
  if (!file) {
    missing.push(`${iconName}(no-export)`);
    continue;
  }
  const inner = parseFile(file);
  if (inner === null) {
    missing.push(`${iconName}(nofile-${file})`);
    continue;
  }
  out += `  ${iconName}: ${JSON.stringify(inner)},\n`;
}
out += '};\n';

writeFileSync(new URL('src/components/iconPaths.ts', ROOT), out);
console.log(`generated: ${names.size} icons (${out.length} bytes)`);
if (missing.length) process.exitCode = 1;